name: Build and upload docker images for a bundler service

on:
  workflow_call:
    inputs:
      bundler-name:
        required: true
        type: string

jobs:
  build-and-upload:
    name: Build and publish images
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_SECRET }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./bundlers/${{ inputs.bundler-name }}
          file: ./bundlers/${{ inputs.bundler-name }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_USERNAME }}/aa-playground:${{ inputs.bundler-name }}-${{ github.sha }}
            ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_USERNAME }}/aa-playground:${{ inputs.bundler-name }}-latest
